# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_arm64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -I. -Isrc -Iinclude -I../editor/thirdpart/imgui-docking -I../editor/thirdpart/imgui-docking/backends -I../engine/include -I../engine -I../enet-1.3.18/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_x64)
TARGETDIR = ../bin/Debug
TARGET = $(TARGETDIR)/liblibsubterra.a
OBJDIR = ../bin-int/libsubterra/Debug/x64
DEFINES += -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g -std=c23
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g -std=c++23
LIBS += ../bin/Debug/libengine.a -lenet -lSDL3 -lrt -lGL -lpthread -lm -ldl -lX11 -lz
LDDEPS += ../bin/Debug/libengine.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),debug_x86)
TARGETDIR = ../bin/Debug
TARGET = $(TARGETDIR)/liblibsubterra.a
OBJDIR = ../bin-int/libsubterra/Debug/x86
DEFINES += -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O0 -g -std=c23
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O0 -g -std=c++23
LIBS += ../bin/Debug/libengine.a -lenet -lSDL3 -lrt -lGL -lpthread -lm -ldl -lX11 -lz
LDDEPS += ../bin/Debug/libengine.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32

else ifeq ($(config),debug_arm64)
TARGETDIR = ../bin/Debug
TARGET = $(TARGETDIR)/liblibsubterra.a
OBJDIR = ../bin-int/libsubterra/Debug/ARM64
DEFINES += -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -g -std=c23
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -g -std=c++23
LIBS += ../bin/Debug/libengine.a -lenet -lSDL3 -lrt -lGL -lpthread -lm -ldl -lX11 -lz
LDDEPS += ../bin/Debug/libengine.a
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),release_x64)
TARGETDIR = ../bin/Release
TARGET = $(TARGETDIR)/liblibsubterra.a
OBJDIR = ../bin-int/libsubterra/Release/x64
DEFINES += -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c23
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++23
LIBS += ../bin/Release/libengine.a -lenet -lSDL3 -lrt -lGL -lpthread -lm -ldl -lX11 -lz
LDDEPS += ../bin/Release/libengine.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s

else ifeq ($(config),release_x86)
TARGETDIR = ../bin/Release
TARGET = $(TARGETDIR)/liblibsubterra.a
OBJDIR = ../bin-int/libsubterra/Release/x86
DEFINES += -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -std=c23
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -std=c++23
LIBS += ../bin/Release/libengine.a -lenet -lSDL3 -lrt -lGL -lpthread -lm -ldl -lX11 -lz
LDDEPS += ../bin/Release/libengine.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32 -s

else ifeq ($(config),release_arm64)
TARGETDIR = ../bin/Release
TARGET = $(TARGETDIR)/liblibsubterra.a
OBJDIR = ../bin-int/libsubterra/Release/ARM64
DEFINES += -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -std=c23
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -std=c++23
LIBS += ../bin/Release/libengine.a -lenet -lSDL3 -lrt -lGL -lpthread -lm -ldl -lX11 -lz
LDDEPS += ../bin/Release/libengine.a
ALL_LDFLAGS += $(LDFLAGS) -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/game.o
GENERATED += $(OBJDIR)/map_event_system.o
GENERATED += $(OBJDIR)/map_events.o
GENERATED += $(OBJDIR)/player_anim_loader.o
GENERATED += $(OBJDIR)/spawn_service.o
GENERATED += $(OBJDIR)/subterra_camera.o
GENERATED += $(OBJDIR)/subterra_console_commands.o
GENERATED += $(OBJDIR)/subterra_day_night.o
GENERATED += $(OBJDIR)/subterra_engine.o
GENERATED += $(OBJDIR)/subterra_gameplay_actions.o
GENERATED += $(OBJDIR)/subterra_imgui.o
GENERATED += $(OBJDIR)/subterra_input_config.o
GENERATED += $(OBJDIR)/subterra_interactable_prefabs.o
GENERATED += $(OBJDIR)/subterra_item_consumable.o
GENERATED += $(OBJDIR)/subterra_item_event_dispatch.o
GENERATED += $(OBJDIR)/subterra_item_light.o
GENERATED += $(OBJDIR)/subterra_item_light_runtime.o
GENERATED += $(OBJDIR)/subterra_level_ecs.o
GENERATED += $(OBJDIR)/subterra_loadout.o
GENERATED += $(OBJDIR)/subterra_mob_brains.o
GENERATED += $(OBJDIR)/subterra_mob_prefabs.o
GENERATED += $(OBJDIR)/subterra_player_vitals.o
GENERATED += $(OBJDIR)/subterra_server_config.o
GENERATED += $(OBJDIR)/subterra_session.o
GENERATED += $(OBJDIR)/subterra_status_effects.o
GENERATED += $(OBJDIR)/subterra_vitals_tick.o
GENERATED += $(OBJDIR)/subterra_world_rules.o
OBJECTS += $(OBJDIR)/game.o
OBJECTS += $(OBJDIR)/map_event_system.o
OBJECTS += $(OBJDIR)/map_events.o
OBJECTS += $(OBJDIR)/player_anim_loader.o
OBJECTS += $(OBJDIR)/spawn_service.o
OBJECTS += $(OBJDIR)/subterra_camera.o
OBJECTS += $(OBJDIR)/subterra_console_commands.o
OBJECTS += $(OBJDIR)/subterra_day_night.o
OBJECTS += $(OBJDIR)/subterra_engine.o
OBJECTS += $(OBJDIR)/subterra_gameplay_actions.o
OBJECTS += $(OBJDIR)/subterra_imgui.o
OBJECTS += $(OBJDIR)/subterra_input_config.o
OBJECTS += $(OBJDIR)/subterra_interactable_prefabs.o
OBJECTS += $(OBJDIR)/subterra_item_consumable.o
OBJECTS += $(OBJDIR)/subterra_item_event_dispatch.o
OBJECTS += $(OBJDIR)/subterra_item_light.o
OBJECTS += $(OBJDIR)/subterra_item_light_runtime.o
OBJECTS += $(OBJDIR)/subterra_level_ecs.o
OBJECTS += $(OBJDIR)/subterra_loadout.o
OBJECTS += $(OBJDIR)/subterra_mob_brains.o
OBJECTS += $(OBJDIR)/subterra_mob_prefabs.o
OBJECTS += $(OBJDIR)/subterra_player_vitals.o
OBJECTS += $(OBJDIR)/subterra_server_config.o
OBJECTS += $(OBJDIR)/subterra_session.o
OBJECTS += $(OBJDIR)/subterra_status_effects.o
OBJECTS += $(OBJDIR)/subterra_vitals_tick.o
OBJECTS += $(OBJDIR)/subterra_world_rules.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking libsubterra
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning libsubterra
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/game.o: src/game.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/map_event_system.o: src/map_event_system.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/map_events.o: src/map_events.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/player_anim_loader.o: src/player_anim_loader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/spawn_service.o: src/spawn_service.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_camera.o: src/subterra_camera.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_console_commands.o: src/subterra_console_commands.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_day_night.o: src/subterra_day_night.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_engine.o: src/subterra_engine.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_gameplay_actions.o: src/subterra_gameplay_actions.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_imgui.o: src/subterra_imgui.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_input_config.o: src/subterra_input_config.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_interactable_prefabs.o: src/subterra_interactable_prefabs.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_item_consumable.o: src/subterra_item_consumable.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_item_event_dispatch.o: src/subterra_item_event_dispatch.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_item_light.o: src/subterra_item_light.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_item_light_runtime.o: src/subterra_item_light_runtime.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_level_ecs.o: src/subterra_level_ecs.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_loadout.o: src/subterra_loadout.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_mob_brains.o: src/subterra_mob_brains.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_mob_prefabs.o: src/subterra_mob_prefabs.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_player_vitals.o: src/subterra_player_vitals.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_server_config.o: src/subterra_server_config.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_session.o: src/subterra_session.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_status_effects.o: src/subterra_status_effects.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_vitals_tick.o: src/subterra_vitals_tick.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/subterra_world_rules.o: src/subterra_world_rules.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif